config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users
  get 'welcome/index'
  root 'articles#index'

  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end

  get '/dashboard', to: "welcome#dashboard"
  put "/articles/:id/publish", to: "articles#publish"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_navigation.html.erb
<header>
  <nav class="be-blue white large-padding bold-font">
    <ul style="list-style-type: none" class="no-list row center-xs middle-xs">
      <li class="col-xs ">
        <h1 class="no-marging no-padding" id="logo"><%= link_to "BLOG ON RAILS", root_path %></h1>
      </li>
      <% @categories.each do |category|%>
          <li class="col-xs">
            <%= link_to category.name, category%>
          </li>
      <% end %>
      <li class="col-xs bold-font">
        <%= link_to "Crear articulo", new_article_path %>
      </li>
      <% if user_signed_in? %>
          <li class="col-xs">
            <%= link_to "Nuevo articulo", new_article_path%>
          </li>
          <li class="col-xs">
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%>
          </li>
      <%else%>
          <li class="col-xs">
            <%= link_to "Iniciar sesión", new_user_session_path%>
          </li>
          <li class="col-xs">
            <%= link_to "Registro", new_user_registration_path%>
          </li>
      <%end%>
    </ul>
  </nav>
</header>